require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CheckSessionsController do

  # This should return the minimal set of attributes required to create a valid
  # CheckSession. As you add validations to CheckSession, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CheckSessionsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all check_sessions as @check_sessions" do
      check_session = CheckSession.create! valid_attributes
      get :index, {}, valid_session
      assigns(:check_sessions).should eq([check_session])
    end
  end

  describe "GET show" do
    it "assigns the requested check_session as @check_session" do
      check_session = CheckSession.create! valid_attributes
      get :show, {:id => check_session.to_param}, valid_session
      assigns(:check_session).should eq(check_session)
    end
  end

  describe "GET new" do
    it "assigns a new check_session as @check_session" do
      get :new, {}, valid_session
      assigns(:check_session).should be_a_new(CheckSession)
    end
  end

  describe "GET edit" do
    it "assigns the requested check_session as @check_session" do
      check_session = CheckSession.create! valid_attributes
      get :edit, {:id => check_session.to_param}, valid_session
      assigns(:check_session).should eq(check_session)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CheckSession" do
        expect {
          post :create, {:check_session => valid_attributes}, valid_session
        }.to change(CheckSession, :count).by(1)
      end

      it "assigns a newly created check_session as @check_session" do
        post :create, {:check_session => valid_attributes}, valid_session
        assigns(:check_session).should be_a(CheckSession)
        assigns(:check_session).should be_persisted
      end

      it "redirects to the created check_session" do
        post :create, {:check_session => valid_attributes}, valid_session
        response.should redirect_to(CheckSession.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved check_session as @check_session" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckSession.any_instance.stub(:save).and_return(false)
        post :create, {:check_session => {  }}, valid_session
        assigns(:check_session).should be_a_new(CheckSession)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CheckSession.any_instance.stub(:save).and_return(false)
        post :create, {:check_session => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested check_session" do
        check_session = CheckSession.create! valid_attributes
        # Assuming there are no other check_sessions in the database, this
        # specifies that the CheckSession created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CheckSession.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => check_session.to_param, :check_session => { "these" => "params" }}, valid_session
      end

      it "assigns the requested check_session as @check_session" do
        check_session = CheckSession.create! valid_attributes
        put :update, {:id => check_session.to_param, :check_session => valid_attributes}, valid_session
        assigns(:check_session).should eq(check_session)
      end

      it "redirects to the check_session" do
        check_session = CheckSession.create! valid_attributes
        put :update, {:id => check_session.to_param, :check_session => valid_attributes}, valid_session
        response.should redirect_to(check_session)
      end
    end

    describe "with invalid params" do
      it "assigns the check_session as @check_session" do
        check_session = CheckSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => check_session.to_param, :check_session => {  }}, valid_session
        assigns(:check_session).should eq(check_session)
      end

      it "re-renders the 'edit' template" do
        check_session = CheckSession.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CheckSession.any_instance.stub(:save).and_return(false)
        put :update, {:id => check_session.to_param, :check_session => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested check_session" do
      check_session = CheckSession.create! valid_attributes
      expect {
        delete :destroy, {:id => check_session.to_param}, valid_session
      }.to change(CheckSession, :count).by(-1)
    end

    it "redirects to the check_sessions list" do
      check_session = CheckSession.create! valid_attributes
      delete :destroy, {:id => check_session.to_param}, valid_session
      response.should redirect_to(check_sessions_url)
    end
  end

end
