require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RouteBuildersController do

  # This should return the minimal set of attributes required to create a valid
  # RouteBuilder. As you add validations to RouteBuilder, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RouteBuildersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all route_builders as @route_builders" do
      route_builder = RouteBuilder.create! valid_attributes
      get :index, {}, valid_session
      assigns(:route_builders).should eq([route_builder])
    end
  end

  describe "GET show" do
    it "assigns the requested route_builder as @route_builder" do
      route_builder = RouteBuilder.create! valid_attributes
      get :show, {:id => route_builder.to_param}, valid_session
      assigns(:route_builder).should eq(route_builder)
    end
  end

  describe "GET new" do
    it "assigns a new route_builder as @route_builder" do
      get :new, {}, valid_session
      assigns(:route_builder).should be_a_new(RouteBuilder)
    end
  end

  describe "GET edit" do
    it "assigns the requested route_builder as @route_builder" do
      route_builder = RouteBuilder.create! valid_attributes
      get :edit, {:id => route_builder.to_param}, valid_session
      assigns(:route_builder).should eq(route_builder)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RouteBuilder" do
        expect {
          post :create, {:route_builder => valid_attributes}, valid_session
        }.to change(RouteBuilder, :count).by(1)
      end

      it "assigns a newly created route_builder as @route_builder" do
        post :create, {:route_builder => valid_attributes}, valid_session
        assigns(:route_builder).should be_a(RouteBuilder)
        assigns(:route_builder).should be_persisted
      end

      it "redirects to the created route_builder" do
        post :create, {:route_builder => valid_attributes}, valid_session
        response.should redirect_to(RouteBuilder.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved route_builder as @route_builder" do
        # Trigger the behavior that occurs when invalid params are submitted
        RouteBuilder.any_instance.stub(:save).and_return(false)
        post :create, {:route_builder => {  }}, valid_session
        assigns(:route_builder).should be_a_new(RouteBuilder)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RouteBuilder.any_instance.stub(:save).and_return(false)
        post :create, {:route_builder => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested route_builder" do
        route_builder = RouteBuilder.create! valid_attributes
        # Assuming there are no other route_builders in the database, this
        # specifies that the RouteBuilder created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RouteBuilder.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => route_builder.to_param, :route_builder => { "these" => "params" }}, valid_session
      end

      it "assigns the requested route_builder as @route_builder" do
        route_builder = RouteBuilder.create! valid_attributes
        put :update, {:id => route_builder.to_param, :route_builder => valid_attributes}, valid_session
        assigns(:route_builder).should eq(route_builder)
      end

      it "redirects to the route_builder" do
        route_builder = RouteBuilder.create! valid_attributes
        put :update, {:id => route_builder.to_param, :route_builder => valid_attributes}, valid_session
        response.should redirect_to(route_builder)
      end
    end

    describe "with invalid params" do
      it "assigns the route_builder as @route_builder" do
        route_builder = RouteBuilder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RouteBuilder.any_instance.stub(:save).and_return(false)
        put :update, {:id => route_builder.to_param, :route_builder => {  }}, valid_session
        assigns(:route_builder).should eq(route_builder)
      end

      it "re-renders the 'edit' template" do
        route_builder = RouteBuilder.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RouteBuilder.any_instance.stub(:save).and_return(false)
        put :update, {:id => route_builder.to_param, :route_builder => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested route_builder" do
      route_builder = RouteBuilder.create! valid_attributes
      expect {
        delete :destroy, {:id => route_builder.to_param}, valid_session
      }.to change(RouteBuilder, :count).by(-1)
    end

    it "redirects to the route_builders list" do
      route_builder = RouteBuilder.create! valid_attributes
      delete :destroy, {:id => route_builder.to_param}, valid_session
      response.should redirect_to(route_builders_url)
    end
  end

end
